### ISSUE TITLE
Stealth reseed transports

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd-reseed#1]
Reseed could upload it's data to popular free hostings/CDNs to avoid I2P block like its done in China.

With that ability ISP could only see that user connects to CDN by HTTPS and nothing more.

Possible hostings: github, dropbox, google sites/Google apps. Needs more research.

I suggest that we write python plugins for reseed server - to add different plugins easily.

**Comment by orignal** [comment]
Go ahead and start implementing. All permissions are granted
